# Generated by Django 5.2.9 on 2025-12-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('base_depth', models.IntegerField(blank=True, help_text='Base snow depth in inches', null=True)),
                ('summit_depth', models.IntegerField(blank=True, help_text='Summit snow depth in inches', null=True)),
                ('new_snow_24h', models.IntegerField(blank=True, help_text='New snow in last 24h (inches)', null=True)),
                ('new_snow_48h', models.IntegerField(blank=True, help_text='New snow in last 48h (inches)', null=True)),
                ('trails_open', models.IntegerField(blank=True, null=True)),
                ('trails_total', models.IntegerField(blank=True, null=True)),
                ('lifts_open', models.IntegerField(blank=True, null=True)),
                ('lifts_total', models.IntegerField(blank=True, null=True)),
                ('acres_open', models.IntegerField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('conditions_updated', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('last_scraped', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='resorts_res_latitud_a3c51a_idx'), models.Index(fields=['state'], name='resorts_res_state_0adbf2_idx'), models.Index(fields=['is_open'], name='resorts_res_is_open_5bad53_idx')],
            },
        ),
    ]
